import type { MenuItem, OrderItem, Order, OrderType } from "@/types/orders"

export function addToOrder(items: OrderItem[], menuItem: MenuItem): OrderItem[] {
  const existing = items.find((i) => i.menuItem.id === menuItem.id)
  if (existing) {
    return items.map((i) =>
      i.menuItem.id === menuItem.id ? { ...i, qty: i.qty + 1 } : i
    )
  }
  return [...items, { menuItem, qty: 1 }]
}

export function removeFromOrder(items: OrderItem[], menuItemId: string): OrderItem[] {
  return items.filter((i) => i.menuItem.id !== menuItemId)
}

export function updateQty(items: OrderItem[], menuItemId: string, qty: number): OrderItem[] {
  if (qty <= 0) return removeFromOrder(items, menuItemId)
  return items.map((i) => (i.menuItem.id === menuItemId ? { ...i, qty } : i))
}

export function calcTotal(items: OrderItem[]): number {
  return items.reduce((sum, i) => sum + i.menuItem.price * i.qty, 0)
}

export function buildOrder(items: OrderItem[], type: OrderType, count: number): Order {
  return {
    id: crypto.randomUUID(),
    orderNumber: `#${String(count).padStart(3, "0")}`,
    items,
    type,
    status: "pending",
    total: calcTotal(items),
    createdAt: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
  }
}

export function filterMenu<T extends { category: string }>(
  items: T[],
  category: string
): T[] {
  if (category === "All") return items
  return items.filter((i) => i.category === category)
}

export function cycleStatus(status: Order["status"]): Order["status"] {
  return "ready"
}



// ************** SUPABASE FUNCTIONS **********************
import { supabase } from "@/lib/supabase/client"

/**
 * Fetch all non-cancelled orders newest first, with their line items.
 * Reconstructs MenuItem from the snapshot fields stored in order_items.
 */
export async function fetchOrders(): Promise<Order[]> {
  const { data, error } = await supabase
    .from("orders")
    .select(`
      id,
      order_number,
      type,
      status,
      total,
      created_at,
      order_items (
        id,
        menu_item_id,
        menu_item_name,
        unit_price,
        qty
      )
    `)
    .neq("status", "cancelled")
    .order("created_at", { ascending: false })

  if (error) throw error

  return (data ?? []).map((row: any) => ({
    id: row.id,
    orderNumber: row.order_number,
    type: row.type as OrderType,
    status: row.status as Order["status"],
    total: row.total,
    createdAt: new Date(row.created_at).toLocaleTimeString([], {
      hour: "2-digit",
      minute: "2-digit",
    }),
    items: (row.order_items ?? []).map((li: any) => ({
      menuItem: {
        // menu_item_id is nullable (SET NULL when item deleted) — fall back to order_item id so React keys are always unique
        id: li.menu_item_id ?? li.id,
        name: li.menu_item_name,
        price: li.unit_price,
        description: "",
        category: "",
      },
      qty: li.qty,
    })),
  }))
}

/**
 * Insert an order + all its line items.
 * - order_number is auto-generated by the DB trigger (trg_order_number)
 * - total is auto-calculated by the DB trigger (trg_order_total)
 * Returns the created order mapped to the app Order type.
 */
export async function placeOrderSupabase(
  items: OrderItem[],
  type: OrderType
): Promise<Order> {
  const { data: { user } } = await supabase.auth.getUser()

  // 1. Create order header
  const { data: order, error: orderErr } = await supabase
    .from("orders")
    .insert({ type, created_by: user?.id ?? null, status: "pending" })
    .select("id, order_number, created_at")
    .single()

  if (orderErr || !order) throw orderErr ?? new Error("Failed to create order")

  // 2. Insert line items (total recalculated by trigger)
  const { error: itemsErr } = await supabase
    .from("order_items")
    .insert(
      items.map(({ menuItem, qty }) => ({
        order_id: order.id,
        menu_item_id: menuItem.id,
        menu_item_name: menuItem.name,
        unit_price: menuItem.price,
        qty,
      }))
    )

  if (itemsErr) throw itemsErr

  return {
    id: order.id,
    orderNumber: order.order_number,
    type,
    status: "pending",
    total: calcTotal(items),
    createdAt: new Date(order.created_at).toLocaleTimeString([], {
      hour: "2-digit",
      minute: "2-digit",
    }),
    items,
  }
}

/** Advance an order's status (pending → ready) or cancel it. */
export async function updateOrderStatusSupabase(
  id: string,
  status: "pending" | "ready" | "cancelled"
): Promise<void> {
  const { error } = await supabase
    .from("orders")
    .update({ status })
    .eq("id", id)
  if (error) throw error
}
